Update multiarch.yml

diff --git a/.github/workflows/multiarch.yml b/.github/workflows/multiarch.yml
--- a/.github/workflows/multiarch.yml
+++ b/.github/workflows/multiarch.yml
@@ -19,7 +19,25 @@ jobs:
     - name: Install dependencies
       run: |
         sudo apt-get update
-        sudo apt-get install -y cmake g++-multilib libboost-all-dev
+        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends cmake g++-multilib libboost-all-dev
+
+    - name: Find and change to src directory
+      id: find-src
+      run: |
+        found=0
+        dir=$(pwd)
+        while [[ "$dir" != "/" ]]; do
+          if [[ -d "$dir/src" ]]; then
+            found=1
+            echo "::set-output name=src-dir::$dir/src"
+            break
+          fi
+          dir=$(dirname "$dir")
+        done
+        if [[ $found -ne 1 ]]; then
+          echo "src directory not found"
+          exit 1
+        fi
 
     - name: Generate random tag
       id: tag
@@ -27,7 +45,7 @@ jobs:
 
     - name: Cross-compile for ${{ matrix.arch }}
       run: |
-        cd ~/src
+        cd ${{ steps.find-src.outputs['src-dir'] }}
         mkdir -p build-${{ matrix.arch }}
         cd build-${{ matrix.arch }}
         cmake .. -DCMAKE_TOOLCHAIN_FILE=../toolchain-${{ matrix.arch }}.cmake
@@ -38,7 +56,7 @@ jobs:
 
     - name: Move compiled binaries to artifacts
       run: |
-        cp ~/src/build-${{ matrix.arch }}/SanityScrew artifacts/SanityScrew_${{ matrix.arch }}
+        cp ${{ steps.find-src.outputs['src-dir'] }}/build-${{ matrix.arch }}/SanityScrew artifacts/SanityScrew_${{ matrix.arch }}
 
     - name: Upload artifacts
       uses: actions/upload-artifact@v2
@@ -55,4 +73,4 @@ jobs:
         token: ${{ secrets.TOKEN }}
 
     - name: Clean up
-      run: rm -rf ~/src/build-${{ matrix.arch }}
+      run: rm -rf ${{ steps.find-src.outputs['src-dir'] }}/build-${{ matrix.arch }}
